export { copySync } from "https://deno.land/std@0.197.0/fs/mod.ts";
export { relative, resolve } from "https://deno.land/std@0.197.0/path/mod.ts";
export { colors } from "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts";
export { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.3/command/mod.ts";
export { transpile } from "https://deno.land/x/emit@0.25.0/mod.ts";
export { type PluginManifest } from "npm:obsidian";
export * as RollupModule from "npm:rollup@3.27.2";
export type { SetRequired, TsConfigJson } from "npm:type-fest";
export { default as packageJson } from "../assets/package.json" assert { type: "json" };
export { default as denoJson } from "../deno.json" assert { type: "json" };
